name: Release

on:
  push:
    tags:
      - 'v*.*.*'

concurrency:
  group: release-publish
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  pipeline:
    permissions:
      contents: write
      packages: write
      id-token: write
    uses: ./.github/workflows/_release-pipeline.yml
    with:
      tag: ${{ github.ref_name }}
